project:
    type: website

website:
    title: 'Felix SOEDJEDE'
    favicon: profile.png
    description: |
        Blog of *Felix SOEDJEDE*, an IT Engineer passionate by `Entrepreneurship`,
        `Software Craftsmanship`, `Clean Code`, `Structured thoughts`, `PHP`, `Symfony`, `Python`, `Pandoc`, etc.
    #email: soefelix[at]gmail.com
    google-analytics: 'G-MHY4PCDZTD'
    navbar:
        background: dark
        pinned: true
        right:
            - about.qmd
            -   icon: github
                href: https://github.com/fsoedjede
            -   icon: twitter
                href: https://twitter.comfsoedjede

format:
    html:
        theme: cosmo
        css: styles.css

# freeze computational output
# https://quarto.org/docs/publishing/github-pages.html#freezing-computations
execute:
    freeze: auto
