---
title: "Why I started contributing to opensource?"
date: 2022-04-27T02:35:00+0200
categories: [opensource]
---

> Disclaimer: This post is a temporary post create during the initialisation of this blog.
> Do not expect the content to be fully relevant or complete.

During my growth as from Junior Developer to Senior Developer and Lead Dev,
I've come across some issues with the libraries I commonly use.

Being Junior Developer, I just dig into the library code to understand the bug and fix my code to make it work.

Growing to Intermediate then Senior Developer, I wanted to contribute to the projects I use to help them improve or add some features I'm missing.
That's how I started following the specific projects I use a lot like Symfony, EasyAdminBundle, etc.

Here, I list those projects and my contribution to them.
This list will be annually updated to help me follow my growth in contributing to opensource.

> One thing I learned contributing to opensource projects is:
> "My time is precious. The projects maintainers time is precious.
> It's easier to fix an issue when the context is clearly established and test case are provided."
